import { AppError } from "./errors.js";

export type StorageProviderName = "host" | "ftp" | "s3" | "r2" | "http";
export interface AppConfig {
  host: string; port: number; corsOrigins: string[]; maxMediaBytes: number;
  reporter: { clientId: string; clientSecret: string; databasePath: string; initialStatus: string; initialStatusLabel: string };
  storage: { providers: StorageProviderName[]; keyPrefix: string; failureMode: "fail" | "continue"; host: { rootPath?: string; publicBaseUrl?: string }; ftp: { host?: string; port: number; secure: boolean; user?: string; password?: string; remotePath: string; publicBaseUrl?: string }; s3: { region: string; bucket?: string; accessKeyId?: string; secretAccessKey?: string; endpoint?: string; publicBaseUrl?: string }; r2: { accountId?: string; bucket?: string; accessKeyId?: string; secretAccessKey?: string; publicBaseUrl?: string }; http: { endpoint?: string; apiKey?: string } };
  github: { enabled: boolean; apiBaseUrl: string; owner?: string; repository?: string; authMode: "token" | "app"; token?: string; appId?: string; installationId?: string; privateKey?: string; labels: string[] };
}
const value = (v: string | undefined) => v?.trim() || undefined;
function positive(v: string | undefined, fallback: number, name: string) { const n = v ? Number(v) : fallback; if (!Number.isSafeInteger(n) || n <= 0) throw new AppError(500, "INVALID_CONFIGURATION", `${name} must be a positive integer.`); return n; }
function providers(v: string | undefined) { const values = [...new Set((v || "").split(",").map((x) => x.trim()).filter(Boolean))]; const allowed = ["host", "ftp", "s3", "r2", "http"] as const; for (const item of values) if (!allowed.includes(item as StorageProviderName)) throw new AppError(500, "INVALID_CONFIGURATION", `Unsupported storage provider: ${item}.`); return values as StorageProviderName[]; }
function requireFields(enabled: StorageProviderName[], provider: StorageProviderName, fields: Array<[string, string | undefined]>) { if (enabled.includes(provider)) for (const [name, field] of fields) if (!field) throw new AppError(500, "INVALID_CONFIGURATION", `${name} is required when ${provider} storage is enabled.`); }
export function loadConfig(env: NodeJS.ProcessEnv = process.env): AppConfig {
  const clientId = value(env.REPORTER_CLIENT_ID), clientSecret = value(env.REPORTER_CLIENT_SECRET);
  if (!clientId || !clientSecret) throw new AppError(500, "INVALID_CONFIGURATION", "REPORTER_CLIENT_ID and REPORTER_CLIENT_SECRET are required.");
  const enabled = providers(env.STORAGE_PROVIDERS), hostRoot = value(env.STORAGE_HOST_ROOT_PATH), hostUrl = value(env.STORAGE_HOST_PUBLIC_BASE_URL), ftpHost = value(env.STORAGE_FTP_HOST), ftpUser = value(env.STORAGE_FTP_USER), ftpPassword = value(env.STORAGE_FTP_PASSWORD), ftpUrl = value(env.STORAGE_FTP_PUBLIC_BASE_URL), s3Bucket = value(env.STORAGE_S3_BUCKET), s3Key = value(env.STORAGE_S3_ACCESS_KEY_ID), s3Secret = value(env.STORAGE_S3_SECRET_ACCESS_KEY), s3Url = value(env.STORAGE_S3_PUBLIC_BASE_URL), r2Account = value(env.STORAGE_R2_ACCOUNT_ID), r2Bucket = value(env.STORAGE_R2_BUCKET), r2Key = value(env.STORAGE_R2_ACCESS_KEY_ID), r2Secret = value(env.STORAGE_R2_SECRET_ACCESS_KEY), r2Url = value(env.STORAGE_R2_PUBLIC_BASE_URL), httpEndpoint = value(env.STORAGE_HTTP_ENDPOINT);
  requireFields(enabled, "host", [["STORAGE_HOST_ROOT_PATH", hostRoot], ["STORAGE_HOST_PUBLIC_BASE_URL", hostUrl]]); requireFields(enabled, "ftp", [["STORAGE_FTP_HOST", ftpHost], ["STORAGE_FTP_USER", ftpUser], ["STORAGE_FTP_PASSWORD", ftpPassword], ["STORAGE_FTP_PUBLIC_BASE_URL", ftpUrl]]); requireFields(enabled, "s3", [["STORAGE_S3_BUCKET", s3Bucket], ["STORAGE_S3_ACCESS_KEY_ID", s3Key], ["STORAGE_S3_SECRET_ACCESS_KEY", s3Secret], ["STORAGE_S3_PUBLIC_BASE_URL", s3Url]]); requireFields(enabled, "r2", [["STORAGE_R2_ACCOUNT_ID", r2Account], ["STORAGE_R2_BUCKET", r2Bucket], ["STORAGE_R2_ACCESS_KEY_ID", r2Key], ["STORAGE_R2_SECRET_ACCESS_KEY", r2Secret], ["STORAGE_R2_PUBLIC_BASE_URL", r2Url]]); requireFields(enabled, "http", [["STORAGE_HTTP_ENDPOINT", httpEndpoint]]);
  const githubEnabled = env.GITHUB_ENABLED === "true", owner = value(env.GITHUB_OWNER), repository = value(env.GITHUB_REPOSITORY), authMode = env.GITHUB_AUTH_MODE === "app" ? "app" : "token", token = value(env.GITHUB_TOKEN), appId = value(env.GITHUB_APP_ID), installationId = value(env.GITHUB_APP_INSTALLATION_ID), privateKey = value(env.GITHUB_APP_PRIVATE_KEY)?.replace(/\\n/g, "\n");
  if (githubEnabled && (!owner || !repository || (authMode === "token" && !token) || (authMode === "app" && (!appId || !installationId || !privateKey)))) throw new AppError(500, "INVALID_CONFIGURATION", "GitHub credentials and repository configuration are incomplete.");
  const initialStatus = value(env.REPORTER_INITIAL_STATUS) || "submitted", initialStatusLabel = value(env.REPORTER_INITIAL_STATUS_LABEL) || "Developer review required";
  return { host: value(env.HOST) || "127.0.0.1", port: positive(env.PORT, 4200, "PORT"), corsOrigins: (env.CORS_ORIGINS || "*").split(",").map((x) => x.trim()).filter(Boolean), maxMediaBytes: positive(env.MAX_MEDIA_BYTES, 50 * 1024 * 1024, "MAX_MEDIA_BYTES"), reporter: { clientId, clientSecret, databasePath: value(env.REPORTER_DATABASE_PATH) || "./firsthand-reporter.sqlite", initialStatus, initialStatusLabel }, storage: { providers: enabled, keyPrefix: value(env.STORAGE_KEY_PREFIX) || "recordings", failureMode: env.STORAGE_FAILURE_MODE === "continue" ? "continue" : "fail", host: { ...(hostRoot ? { rootPath: hostRoot } : {}), ...(hostUrl ? { publicBaseUrl: hostUrl } : {}) }, ftp: { ...(ftpHost ? { host: ftpHost } : {}), port: positive(env.STORAGE_FTP_PORT, 21, "STORAGE_FTP_PORT"), secure: env.STORAGE_FTP_SECURE === "true", ...(ftpUser ? { user: ftpUser } : {}), ...(ftpPassword ? { password: ftpPassword } : {}), remotePath: value(env.STORAGE_FTP_REMOTE_PATH) || "/", ...(ftpUrl ? { publicBaseUrl: ftpUrl } : {}) }, s3: { region: value(env.STORAGE_S3_REGION) || "us-east-1", ...(s3Bucket ? { bucket: s3Bucket } : {}), ...(s3Key ? { accessKeyId: s3Key } : {}), ...(s3Secret ? { secretAccessKey: s3Secret } : {}), ...(value(env.STORAGE_S3_ENDPOINT) ? { endpoint: value(env.STORAGE_S3_ENDPOINT) } : {}), ...(s3Url ? { publicBaseUrl: s3Url } : {}) }, r2: { ...(r2Account ? { accountId: r2Account } : {}), ...(r2Bucket ? { bucket: r2Bucket } : {}), ...(r2Key ? { accessKeyId: r2Key } : {}), ...(r2Secret ? { secretAccessKey: r2Secret } : {}), ...(r2Url ? { publicBaseUrl: r2Url } : {}) }, http: { ...(httpEndpoint ? { endpoint: httpEndpoint } : {}), ...(value(env.STORAGE_HTTP_API_KEY) ? { apiKey: value(env.STORAGE_HTTP_API_KEY) } : {}) } }, github: { enabled: githubEnabled, apiBaseUrl: value(env.GITHUB_API_BASE_URL) || "https://api.github.com", ...(owner ? { owner } : {}), ...(repository ? { repository } : {}), authMode, ...(token ? { token } : {}), ...(appId ? { appId } : {}), ...(installationId ? { installationId } : {}), ...(privateKey ? { privateKey } : {}), labels: (env.GITHUB_ISSUE_LABELS || "firsthand").split(",").map((x) => x.trim()).filter(Boolean) } };
}
