import Database from "better-sqlite3";
import type { PreparedReport } from "./types.js";
export interface StoredIssue { reportId: string; clientId: string; userIdentifier: string; owner: string; repository: string; issueNumber: number; issueUrl: string; title: string; state: string; workflowStatus: string; workflowStatusLabel: string; createdAt: string; updatedAt: string; }
export interface StoredComment { githubCommentId: number; body: string; authorLogin: string; createdAt: string; updatedAt: string; }
export class ReporterDatabase { private database: Database.Database; constructor(path: string) { this.database = new Database(path); this.database.pragma("journal_mode = WAL"); this.database.exec(`CREATE TABLE IF NOT EXISTS reporter_issues (report_id TEXT PRIMARY KEY, client_id TEXT NOT NULL, user_identifier TEXT NOT NULL, github_owner TEXT NOT NULL, github_repository TEXT NOT NULL, github_issue_number INTEGER NOT NULL UNIQUE, github_issue_url TEXT NOT NULL, title TEXT NOT NULL, state TEXT NOT NULL, workflow_status TEXT NOT NULL DEFAULT 'submitted', workflow_status_label TEXT NOT NULL DEFAULT 'Developer review required', report_json TEXT NOT NULL, evidence_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS reporter_issues_client_user ON reporter_issues(client_id, user_identifier, updated_at DESC); CREATE TABLE IF NOT EXISTS reporter_comments (github_comment_id INTEGER PRIMARY KEY, report_id TEXT NOT NULL, body TEXT NOT NULL, author_login TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS reporter_comments_report ON reporter_comments(report_id, created_at ASC);`); for (const column of ["workflow_status TEXT NOT NULL DEFAULT 'submitted'", "workflow_status_label TEXT NOT NULL DEFAULT 'Developer review required'"]) try { this.database.exec(`ALTER TABLE reporter_issues ADD COLUMN ${column}`); } catch (error) { if (!(error instanceof Error) || !error.message.includes("duplicate column name")) throw error; } }
  createIssue(issue: StoredIssue, report: PreparedReport, evidence: unknown) { this.database.prepare(`INSERT INTO reporter_issues (report_id, client_id, user_identifier, github_owner, github_repository, github_issue_number, github_issue_url, title, state, workflow_status, workflow_status_label, report_json, evidence_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(issue.reportId, issue.clientId, issue.userIdentifier, issue.owner, issue.repository, issue.issueNumber, issue.issueUrl, issue.title, issue.state, issue.workflowStatus, issue.workflowStatusLabel, JSON.stringify(report), JSON.stringify(evidence), issue.createdAt, issue.updatedAt); }
  listIssues(clientId: string, user: string) { return this.database.prepare(`SELECT report_id AS reportId, client_id AS clientId, user_identifier AS userIdentifier, github_owner AS owner, github_repository AS repository, github_issue_number AS issueNumber, github_issue_url AS issueUrl, title, state, workflow_status AS workflowStatus, workflow_status_label AS workflowStatusLabel, created_at AS createdAt, updated_at AS updatedAt FROM reporter_issues WHERE client_id = ? AND user_identifier = ? ORDER BY updated_at DESC`).all(clientId, user) as StoredIssue[]; }
  getIssue(clientId: string, reportId: string) { return this.database.prepare(`SELECT report_id AS reportId, client_id AS clientId, user_identifier AS userIdentifier, github_owner AS owner, github_repository AS repository, github_issue_number AS issueNumber, github_issue_url AS issueUrl, title, state, workflow_status AS workflowStatus, workflow_status_label AS workflowStatusLabel, created_at AS createdAt, updated_at AS updatedAt FROM reporter_issues WHERE client_id = ? AND report_id = ?`).get(clientId, reportId) as StoredIssue | undefined; }
  upsertComments(reportId: string, comments: StoredComment[]) { const save = this.database.prepare(`INSERT INTO reporter_comments (github_comment_id, report_id, body, author_login, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(github_comment_id) DO UPDATE SET body = excluded.body, author_login = excluded.author_login, updated_at = excluded.updated_at`); this.database.transaction(() => comments.forEach((c) => save.run(c.githubCommentId, reportId, c.body, c.authorLogin, c.createdAt, c.updatedAt)))(); }
  listComments(reportId: string) { return this.database.prepare(`SELECT github_comment_id AS githubCommentId, body, author_login AS authorLogin, created_at AS createdAt, updated_at AS updatedAt FROM reporter_comments WHERE report_id = ? ORDER BY created_at ASC`).all(reportId) as StoredComment[]; }
}
