import { createSign } from "node:crypto";
import { AppError } from "./errors.js";
import type { AppConfig } from "./config.js";
import type { PreparedReport } from "./types.js";
import type { StoredComment } from "./database.js";
type GitHubIssue = { number: number; html_url: string; title: string; state: string; created_at: string; updated_at: string };
let installationToken: { value: string; expiresAt: number } | undefined;
const base64url = (value: string) => Buffer.from(value).toString("base64url");
function appJwt(config: AppConfig["github"]) { const now = Math.floor(Date.now() / 1000), header = base64url(JSON.stringify({ alg: "RS256", typ: "JWT" })), payload = base64url(JSON.stringify({ iat: now - 60, exp: now + 540, iss: config.appId })), signer = createSign("RSA-SHA256"); signer.update(`${header}.${payload}`); return `${header}.${payload}.${signer.sign(config.privateKey!, "base64url")}`; }
async function token(config: AppConfig["github"]) { if (config.authMode === "token") return config.token!; if (installationToken && installationToken.expiresAt > Date.now() + 60_000) return installationToken.value; const response = await fetch(`${config.apiBaseUrl.replace(/\/$/, "")}/app/installations/${config.installationId}/access_tokens`, { method: "POST", headers: { accept: "application/vnd.github+json", authorization: `Bearer ${appJwt(config)}`, "x-github-api-version": "2026-03-10" } }); const body = await response.json().catch(() => null) as { token?: string; expires_at?: string; message?: string } | null; if (!response.ok || !body?.token || !body.expires_at) throw new AppError(502, "GITHUB_AUTH_FAILED", body?.message || "GitHub App authentication failed."); installationToken = { value: body.token, expiresAt: Date.parse(body.expires_at) }; return body.token; }
export class GitHubIssueClient {
  constructor(private config: AppConfig["github"]) {}
  private async request(path: string, init: RequestInit = {}) { const response = await fetch(`${this.config.apiBaseUrl.replace(/\/$/, "")}${path}`, { ...init, headers: { accept: "application/vnd.github+json", authorization: `Bearer ${await token(this.config)}`, "x-github-api-version": "2026-03-10", ...(init.headers || {}) } }); if (!response.ok) { const body = await response.json().catch(() => null) as { message?: string } | null; throw new AppError(502, "GITHUB_REQUEST_FAILED", body?.message || `GitHub returned status ${response.status}.`); } return response; }
  async createIssue(report: PreparedReport, evidenceUrl: string | undefined, reportId: string, workflowStatus: string, workflowStatusLabel: string) { const body = [`<!-- firsthand:report-id=${reportId} -->`, `## Firsthand status\n${workflowStatus} — ${workflowStatusLabel}`, `## Summary\n${report.summary}`, `## Steps to reproduce\n${report.stepsToReproduce.length ? report.stepsToReproduce.map((step) => `- ${step}`).join("\n") : "Not provided."}`, `## Expected behaviour\n${report.expectedBehaviour || "Not provided."}`, `## Actual behaviour\n${report.actualBehaviour || "Not provided."}`, evidenceUrl ? `## Recording\n${evidenceUrl}` : ""].filter(Boolean).join("\n\n"); const response = await this.request(`/repos/${encodeURIComponent(this.config.owner!)}/${encodeURIComponent(this.config.repository!)}/issues`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: report.title, body, labels: this.config.labels }) }); return response.json() as Promise<GitHubIssue>; }
  async listComments(issue: number) { const response = await this.request(`/repos/${encodeURIComponent(this.config.owner!)}/${encodeURIComponent(this.config.repository!)}/issues/${issue}/comments?per_page=100`); const comments = await response.json() as Array<{ id: number; body: string; user?: { login?: string }; created_at: string; updated_at: string }>; return comments.map((c) => ({ githubCommentId: c.id, body: c.body, authorLogin: c.user?.login || "unknown", createdAt: c.created_at, updatedAt: c.updated_at })); }
  async createComment(issue: number, body: string) { const response = await this.request(`/repos/${encodeURIComponent(this.config.owner!)}/${encodeURIComponent(this.config.repository!)}/issues/${issue}/comments`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ body }) }); const c = await response.json() as { id: number; body: string; user?: { login?: string }; created_at: string; updated_at: string }; return { githubCommentId: c.id, body: c.body, authorLogin: c.user?.login || "unknown", createdAt: c.created_at, updatedAt: c.updated_at } satisfies StoredComment; }
}
