import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, relative, resolve } from "node:path";
import { Readable } from "node:stream";
import { PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import * as ftp from "basic-ftp";
import { AppError } from "./errors.js";
import type { AppConfig } from "./config.js";
import type { UploadedMedia } from "./types.js";

export interface EvidenceLocation { provider: string; key: string; url: string; }
export interface StoreResult { requestId: string; status: "completed" | "partial"; video: { fileName: string; mimeType: string; bytes: number; locations: EvidenceLocation[] }; failures: Array<{ provider: string; message: string }>; }
type StoreInput = { media: UploadedMedia; key: string; metadata: Record<string, unknown> };
interface Provider { name: string; store(input: StoreInput): Promise<EvidenceLocation>; }
const url = (base: string, key: string) => `${base.replace(/\/$/, "")}/${key.split("/").map(encodeURIComponent).join("/")}`;
const keyFor = (prefix: string, name: string) => `${prefix.replace(/^\/+|\/+$/g, "")}/${createHash("sha256").update(`${Date.now()}-${Math.random()}-${name}`).digest("hex").slice(0, 24)}-${basename(name).replace(/[^a-zA-Z0-9._-]/g, "_") || "recording.webm"}`;
class Host implements Provider { readonly name = "host"; constructor(private rootPath: string, private baseUrl: string) {} async store(input: StoreInput) { const root = resolve(this.rootPath), target = resolve(root, input.key), rel = relative(root, target); if (!rel || rel.startsWith("..") || rel.includes(":")) throw new AppError(400, "INVALID_STORAGE_KEY", "The evidence storage key is invalid."); await mkdir(resolve(target, ".."), { recursive: true }); await writeFile(target, input.media.buffer); return { provider: this.name, key: input.key, url: url(this.baseUrl, input.key) }; } }
class Http implements Provider { readonly name = "http"; constructor(private endpoint: string, private apiKey?: string) {} async store(input: StoreInput) { const form = new FormData(); form.set("file", new Blob([new Uint8Array(input.media.buffer)], { type: input.media.mimeType }), input.media.fileName); form.set("key", input.key); form.set("metadata", JSON.stringify(input.metadata)); let response: Response; try { response = await fetch(this.endpoint, { method: "POST", headers: this.apiKey ? { authorization: `Bearer ${this.apiKey}` } : {}, body: form }); } catch (error) { throw new AppError(502, "EVIDENCE_STORAGE_FAILED", "HTTP storage failed.", error); } const body = await response.json().catch(() => null); if (!response.ok || !body || typeof body !== "object" || !("url" in body) || typeof body.url !== "string") throw new AppError(502, "EVIDENCE_STORAGE_FAILED", "HTTP storage must return JSON with a url field."); return { provider: this.name, key: "key" in body && typeof body.key === "string" ? body.key : input.key, url: body.url }; } }
class Ftp implements Provider { readonly name = "ftp"; constructor(private config: AppConfig["storage"]["ftp"]) {} async store(input: StoreInput) { const client = new ftp.Client(); try { await client.access({ host: this.config.host!, port: this.config.port, user: this.config.user!, password: this.config.password!, secure: this.config.secure }); const path = `${this.config.remotePath.replace(/\/$/, "")}/${input.key}`; await client.ensureDir(path.split("/").slice(0, -1).join("/") || "/"); await client.uploadFrom(Readable.from(input.media.buffer), path); return { provider: this.name, key: input.key, url: url(this.config.publicBaseUrl!, input.key) }; } catch (error) { throw new AppError(502, "EVIDENCE_STORAGE_FAILED", "FTP storage failed.", error); } finally { client.close(); } } }
class S3 implements Provider { readonly client: S3Client; constructor(readonly name: "s3" | "r2", private config: { region: string; bucket: string; accessKeyId: string; secretAccessKey: string; endpoint?: string; publicBaseUrl: string }) { this.client = new S3Client({ region: config.region, ...(config.endpoint ? { endpoint: config.endpoint } : {}), credentials: { accessKeyId: config.accessKeyId, secretAccessKey: config.secretAccessKey } }); } async store(input: StoreInput) { try { await this.client.send(new PutObjectCommand({ Bucket: this.config.bucket, Key: input.key, Body: input.media.buffer, ContentType: input.media.mimeType, Metadata: { firsthand: "true" } })); return { provider: this.name, key: input.key, url: url(this.config.publicBaseUrl, input.key) }; } catch (error) { throw new AppError(502, "EVIDENCE_STORAGE_FAILED", `${this.name} storage failed.`, error); } } }
export class EvidenceStorage {
  private providers: Provider[];
  constructor(private config: AppConfig) { this.providers = config.storage.providers.map((provider) => { if (provider === "host") return new Host(config.storage.host.rootPath!, config.storage.host.publicBaseUrl!); if (provider === "http") return new Http(config.storage.http.endpoint!, config.storage.http.apiKey); if (provider === "ftp") return new Ftp(config.storage.ftp); if (provider === "s3") return new S3("s3", { region: config.storage.s3.region, bucket: config.storage.s3.bucket!, accessKeyId: config.storage.s3.accessKeyId!, secretAccessKey: config.storage.s3.secretAccessKey!, ...(config.storage.s3.endpoint ? { endpoint: config.storage.s3.endpoint } : {}), publicBaseUrl: config.storage.s3.publicBaseUrl! }); return new S3("r2", { region: "auto", bucket: config.storage.r2.bucket!, accessKeyId: config.storage.r2.accessKeyId!, secretAccessKey: config.storage.r2.secretAccessKey!, endpoint: `https://${config.storage.r2.accountId!}.r2.cloudflarestorage.com`, publicBaseUrl: config.storage.r2.publicBaseUrl! }); }); }
  async store(video: UploadedMedia, metadata: Record<string, unknown>): Promise<StoreResult> { if (!this.providers.length) throw new AppError(503, "EVIDENCE_STORAGE_DISABLED", "No evidence storage provider is configured."); const locations: EvidenceLocation[] = [], failures: StoreResult["failures"] = [], key = keyFor(this.config.storage.keyPrefix, video.fileName); for (const provider of this.providers) try { locations.push(await provider.store({ media: video, key, metadata })); } catch (error) { if (this.config.storage.failureMode === "fail") throw error; failures.push({ provider: provider.name, message: error instanceof Error ? error.message : "Unknown storage failure" }); } return { requestId: `evidence_${crypto.randomUUID()}`, status: failures.length ? "partial" : "completed", video: { fileName: video.fileName, mimeType: video.mimeType, bytes: video.buffer.length, locations }, failures }; }
  async readHostFile(key: string) { if (!this.config.storage.providers.includes("host") || !this.config.storage.host.rootPath) return undefined; const root = resolve(this.config.storage.host.rootPath), target = resolve(root, key), rel = relative(root, target); if (!key || rel.startsWith("..") || rel.includes(":")) return undefined; return readFile(target).catch(() => undefined); }
}
